 version: '2'
 services:
   prerender:
     build: .
     ports:
      - "3001:3001"
     environment:
       - REDISTOGO_URL=redis://redis:6379/0
       - PORT=3001
     depends_on:
      - redis
   redis:
     image: redis
